In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import warnings
warnings.filterwarnings("ignore")
sns.set()

from sklearn.linear_model import LogisticRegression

from scipy import stats
stats.chisqprob = lambda chisq, df: stats.chi2.sf(chisq, df)

In [3]:
data = pd.read_csv("C:/Users/Eric.Niyitanga/Downloads/Predicting Heart disease/train.csv")
data.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence

In [5]:
data.isna().sum()

id                         0
Age                        0
Sex                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
Exercise angina            0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Heart Disease              0
dtype: int64

In [9]:
data[data.duplicated()]

Empty DataFrame
Columns: [id, Age, Sex, Chest pain type, BP, Cholesterol, FBS over 120, EKG results, Max HR, Exercise angina, ST depression, Slope of ST, Number of vessels fluro, Thallium, Heart Disease]
Index: []

In [55]:
df= data.copy()

In [56]:
df['Heart Disease']= df['Heart Disease'].map({'Presence':1, 'Absence':0})
df.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,1
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,0
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,0
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,0
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,1

In [57]:
df.describe()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,314999.500000,54.136706,0.714735,3.312752,130.497433,245.011814,0.079987,0.981660,152.816763,0.273725,0.716028,1.455871,0.451040,4.618873,0.448340
std,181865.479132,8.256301,0.451541,0.851615,14.975802,33.681581,0.271274,0.998783,19.112927,0.445870,0.948472,0.545192,0.798549,1.950007,0.497324
min,0.000000,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000
25%,157499.750000,48.000000,0.000000,3.000000,120.000000,223.000000,0.000000,0.000000,142.000000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000
50%,314999.500000,54.000000,1.000000,4.000000,130.000000,243.000000,0.000000,0.000000,157.000000,0.000000,0.100000,1.000000,0.000000,3.000000,0.000000
75%,472499.250000,60.000000,1.000000,4.000000,140.000000,269.000000,0.000000,2.000000,166.000000,1.000000,1.400000,2.000000,1.000000,7.000000,1.000000
max,629999.000000,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,7.000000,1.000000

In [58]:
# df = df.drop('id', axis=1)

In [59]:
df.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,1
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,0
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,0
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,0
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,1

In [60]:
y = df['Heart Disease']
x = df.drop('Heart Disease', axis=1)

In [61]:
model = LogisticRegression()
model.fit(x,y)

LogisticRegression()

In [62]:
model.predict(x)

array([1, 0, 0, ..., 1, 0, 0], shape=(630000,))

In [63]:
x1 = sm.add_constant(x)
models = sm.Logit(y,x1).fit()
models.summary()

Optimization terminated successfully.
         Current function value: 0.281742
         Iterations 8

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:          Heart Disease   No. Observations:               630000
Model:                          Logit   Df Residuals:                   629985
Method:                           MLE   Df Model:                           14
Date:                Sun, 15 Mar 2026   Pseudo R-squ.:                  0.5904
Time:                        12:17:54   Log-Likelihood:            -1.7750e+05
converged:                       True   LL-Null:                   -4.3331e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -5.6036      0.074    -75.501      0.000      -5.749      -5.458
id                      -2.034e-08   2.37e-08     -0.859      0.390   -6.67e-08    2.61e-08
Age                         0.0426      0.001     79.831      0.000       0.042       0.044
Sex                         1.0717      0.010    102.446      0.000       1.051       1.092
Chest pain type             1.0431      0.006    172.968      0.000       1.031       1.055
BP                          0.0003      0.000      0.947      0.344      -0.000       0.001
Cholesterol                 0.0029      0.000     22.431      0.000       0.003       0.003
FBS over 120               -0.0404      0.016     -2.523      0.012      -0.072      -0.009
EKG results                 0.2191      0.004     50.764      0.000       0.211       0.228
Max HR                     -0.0438      0.000   -168.818      0.000      -0.044      -0.043
Exercise angina             1.2152      0.010    118.203      0.000       1.195       1.235
ST depression               0.4868      0.005     90.374      0.000       0.476       0.497
Slope of ST                 0.8135      0.008     96.407      0.000       0.797       0.830
Number of vessels fluro     0.8830      0.007    131.820      0.000       0.870       0.896
Thallium                    0.4943      0.002    222.263      0.000       0.490       0.499
===========================================================================================
"""

In [64]:
def confusion_matrix(data, actual_values, model):
    pred_values= model.predict(data)
    bins = np.array([0,0.5,1])
    cm = np.histogram2d(actual_values, pred_values, bins= bins)[0]
    accuracy = (cm[0,0] + cm[1,1])/cm.sum()
    return cm, accuracy

In [65]:
confusion_matrix(x1, y, models)

(array([[314476.,  33070.],
        [ 40559., 241895.]]),
 np.float64(0.8831285714285714))

In [71]:
d_test = pd.read_csv('C:\\Users\\Eric.Niyitanga\\Downloads\\Predicting Heart disease\\test.csv')
# d_test1 = d_test.drop('id', axis=1)
d_test.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
0,630000,58,1,3,120,288,0,2,145,1,0.8,2,3,3
1,630001,55,0,2,120,209,0,0,172,0,0.0,1,0,3
2,630002,54,1,4,120,268,0,0,150,1,0.0,2,3,7
3,630003,44,0,3,112,177,0,0,168,0,0.9,1,0,3
4,630004,43,1,1,138,267,0,0,163,0,1.8,2,0,7

In [72]:
d_test.describe()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.00000,270000.000000
mean,764999.500000,54.159870,0.716315,3.315107,130.555089,245.045270,0.080052,0.978493,152.783756,0.274656,0.718082,1.459356,0.45480,4.619774
std,77942.430678,8.255471,0.450787,0.851762,15.007908,33.695458,0.271374,0.998686,19.153454,0.446341,0.947417,0.546186,0.80127,1.950273
min,630000.000000,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.00000,3.000000
25%,697499.750000,48.000000,0.000000,3.000000,120.000000,223.000000,0.000000,0.000000,142.000000,0.000000,0.000000,1.000000,0.00000,3.000000
50%,764999.500000,54.000000,1.000000,4.000000,130.000000,243.000000,0.000000,0.000000,157.000000,0.000000,0.100000,1.000000,0.00000,3.000000
75%,832499.250000,60.000000,1.000000,4.000000,140.000000,269.000000,0.000000,2.000000,166.000000,1.000000,1.400000,2.000000,1.00000,7.000000
max,899999.000000,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.00000,7.000000

In [73]:
model.predict(d_test)

array([1, 0, 1, ..., 0, 0, 0], shape=(270000,))

In [74]:
d_test['predict'] = model.predict(d_test)

In [75]:

# pd.set_option('display.max_rows', None) # this codes runs all obervations
# pd.set_option('display.max_columns', None) # This code runs all observations

d_test.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,predict
0,630000,58,1,3,120,288,0,2,145,1,0.8,2,3,3,1
1,630001,55,0,2,120,209,0,0,172,0,0.0,1,0,3,0
2,630002,54,1,4,120,268,0,0,150,1,0.0,2,3,7,1
3,630003,44,0,3,112,177,0,0,168,0,0.9,1,0,3,0
4,630004,43,1,1,138,267,0,0,163,0,1.8,2,0,7,0

In [76]:
results= d_test[['id','predict']]

In [80]:
results.to_csv('C:/Users/Eric.Niyitanga/Downloads/Predicting Heart disease/Results.csv, index=False')

In [88]:
d_test.groupby('Sex')['predict'].mean().sort_values(ascending=False)

Sex
1    0.460159
0    0.263725
Name: predict, dtype: float64